"""Initial schema with all tables

Revision ID: 9feae9951ae6
Revises:
Create Date: 2026-08-05 21:08:20.266490

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9feae9951ae6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calc_calculations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_name", sa.String(), nullable=True),
        sa.Column("client_phone", sa.String(), nullable=True),
        sa.Column("markup_percent", sa.Float(), nullable=False),
        sa.Column("overhead_percent", sa.Float(), nullable=False),
        sa.Column("labor_mode", sa.String(), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("sale_price", sa.Float(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "calc_materials",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("grade", sa.String(), nullable=True),
        sa.Column("thickness", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("price_per_m2", sa.Float(), nullable=False),
        sa.Column("waste_factor", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "calc_settings",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("position", sa.String(), nullable=True),
        sa.Column("base_salary", sa.Float(), nullable=True),
        sa.Column("bonus_percent", sa.Float(), nullable=False),
        sa.Column("actual_salary", sa.Float(), nullable=True),
        sa.Column("hired_date", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "overhead_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_number", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("client", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("ventilation_type", sa.String(), nullable=True),
        sa.Column("air_flow", sa.Float(), nullable=True),
        sa.Column("pressure", sa.Float(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("total_area", sa.Float(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_number"),
    )
    op.create_table(
        "calc_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("calculation_id", sa.Integer(), nullable=False),
        sa.Column("subtype_id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("size_params", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("area_m2", sa.Float(), nullable=False),
        sa.Column("material_cost", sa.Float(), nullable=False),
        sa.Column("flange_cost", sa.Float(), nullable=False),
        sa.Column("labor_cost", sa.Float(), nullable=False),
        sa.Column("overhead_cost", sa.Float(), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["calculation_id"],
            ["calc_calculations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "calculations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("calculation_type", sa.String(), nullable=True),
        sa.Column("materials_cost", sa.Float(), nullable=False),
        sa.Column("components_cost", sa.Float(), nullable=False),
        sa.Column("works_cost", sa.Float(), nullable=False),
        sa.Column("overhead_cost", sa.Float(), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("markup_amount", sa.Float(), nullable=False),
        sa.Column("vat_amount", sa.Float(), nullable=False),
        sa.Column("final_price", sa.Float(), nullable=False),
        sa.Column("profit", sa.Float(), nullable=False),
        sa.Column("calculated_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_subtypes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_type_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("formula", sa.String(), nullable=False),
        sa.Column("shape_type", sa.String(), nullable=False),
        sa.Column("flange_perimeter_formula", sa.String(), nullable=True),
        sa.Column("waste_factor", sa.Float(), nullable=False),
        sa.Column("labor_norm", sa.Float(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_type_id"],
            ["product_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "project_components",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("component_name", sa.String(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=True),
        sa.Column("total_price", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_materials",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("material_name", sa.String(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=True),
        sa.Column("total_price", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_works",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("work_name", sa.String(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("unit_price", sa.Float(), nullable=True),
        sa.Column("total_price", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "size_ranges",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subtype_id", sa.Integer(), nullable=False),
        sa.Column("param_name", sa.String(), nullable=False),
        sa.Column("param_label", sa.String(), nullable=False),
        sa.Column("min_value", sa.Float(), nullable=True),
        sa.Column("max_value", sa.Float(), nullable=True),
        sa.Column("step", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("values_json", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["subtype_id"],
            ["product_subtypes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subtype_materials",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subtype_id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["calc_materials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subtype_id"],
            ["product_subtypes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subtype_materials")
    op.drop_table("size_ranges")
    op.drop_table("project_works")
    op.drop_table("project_materials")
    op.drop_table("project_components")
    op.drop_table("product_subtypes")
    op.drop_table("calculations")
    op.drop_table("calc_items")
    op.drop_table("projects")
    op.drop_table("product_types")
    op.drop_table("overhead_items")
    op.drop_table("employees")
    op.drop_table("calc_settings")
    op.drop_table("calc_materials")
    op.drop_table("calc_calculations")
    # ### end Alembic commands ###
